name: generate-taginfo
on:
    push:
    schedule:
        - cron: '0 0 * * *'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo content
            uses: actions/checkout@v2
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: '3.9.16'
          - name: execute py script
            run: python generate-taginfo.py
          - name: commit files
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add -A
              if [[ `git status --porcelain` ]]; then
                git commit -a -m "Update taginfo.json"
                git push
              else
                echo "taginfo.json is up to date, nothing to push"
              fi